# Generated by Django 4.1.3 on 2022-12-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_child_tag_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(max_length=4, null=True)),
                ('attack', models.IntegerField(max_length=4, null=True)),
                ('defense', models.IntegerField(max_length=4, null=True)),
                ('strength', models.IntegerField(max_length=4, null=True)),
                ('hitpoints', models.IntegerField(max_length=4, null=True)),
                ('ranged', models.IntegerField(max_length=4, null=True)),
                ('prayer', models.IntegerField(max_length=4, null=True)),
                ('magic', models.IntegerField(max_length=4, null=True)),
                ('cooking', models.IntegerField(max_length=4, null=True)),
                ('woodcutting', models.IntegerField(max_length=4, null=True)),
                ('fletching', models.IntegerField(max_length=4, null=True)),
                ('fishing', models.IntegerField(max_length=4, null=True)),
                ('firemaking', models.IntegerField(max_length=4, null=True)),
                ('crafting', models.IntegerField(max_length=4, null=True)),
                ('smithing', models.IntegerField(max_length=4, null=True)),
                ('mining', models.IntegerField(max_length=4, null=True)),
                ('herblore', models.IntegerField(max_length=4, null=True)),
                ('agility', models.IntegerField(max_length=4, null=True)),
                ('thieving', models.IntegerField(max_length=4, null=True)),
                ('slayer', models.IntegerField(max_length=4, null=True)),
                ('farming', models.IntegerField(max_length=4, null=True)),
                ('runecrafting', models.IntegerField(max_length=4, null=True)),
                ('hunter', models.IntegerField(max_length=4, null=True)),
                ('construction', models.IntegerField(max_length=4, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
