# Generated by Django 4.1.3 on 2022-12-07 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_skilllevels_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255, null=True)),
                ('activity', models.CharField(max_length=50, null=True)),
                ('players_needed', models.IntegerField(null=True)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
