# Generated by Django 4.1.3 on 2022-12-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_groupfinder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfinder',
            name='user',
        ),
    ]
