# Generated by Django 4.1.3 on 2022-12-07 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_groupfinder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupfinder',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
