# Generated by Django 4.1.3 on 2022-12-06 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_skilllevels_user_customuser_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='skill',
        ),
        migrations.AddField(
            model_name='skilllevels',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
