# Generated by Django 4.1.3 on 2022-12-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_groupfinder_user_groupfinder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfinder',
            name='time_posted',
        ),
    ]
