# Generated by Django 4.1.3 on 2022-12-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_groupfinder_time_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupfinder',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
