# Generated by Django 4.1.3 on 2022-12-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_groupfindercomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfindercomments',
            name='post',
        ),
        migrations.AddField(
            model_name='groupfindercomments',
            name='post',
            field=models.ManyToManyField(to='api.groupfinder'),
        ),
    ]
