# Generated by Django 4.1.3 on 2022-12-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_groupfindercomments_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfindercomments',
            name='post',
        ),
        migrations.AddField(
            model_name='groupfinder',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groupfindercomments'),
        ),
    ]
