# Generated by Django 4.1.3 on 2022-12-09 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_groupfindercomments_post_groupfinder_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfinder',
            name='comment',
        ),
        migrations.AddField(
            model_name='groupfindercomments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groupfinder'),
        ),
    ]
